version: "3.5"

services:
  royale:
    container_name: royale
    networks: 
      nginx
    image: royale
    environment:
      - VIRTUAL_HOST=royale.linhaobin.com
      - VIRTUAL_PORT=80

networks:
  nginx:
    external: true
    name: nginx
  